# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LcloudPro
email: lcloudprok@gmail.com
description: "We are passionate about learn technologies and share knowledge"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Lcloudpro.github.io/New-site1/" # the base hostname & protocol for your site
twitter_username: LcloudproK
github_username:  Lcloudpro

# Build settings
markdown: kramdown

permalink: none
comments: true 
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Latheesh"
      category: "Latheesh"
